language: node_js

node_js:
  - stable

before_install:
  - chmod +x node_modules/istanbul/lib/cli.js
  - chmod +x node_modules/coveralls/bin/coveralls.js
  
install:
  - npm install

script:
  - npm run cover
