language: node_js

sudo: enabled

node_js:
  - stable

install:
  - npm install

script:
  - npm run cover
  
#send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"